services:
  postgres:
    image: bitnami/postgresql:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: budgetbuddy
    volumes:
      - postgres_data:/bitnami/postgresql

  app:
    build: .
    ports:
      - '3333:3333'
    environment:
      DATABASE_CLIENT: pg
      DATABASE_URL: postgresql://docker:docker@postgres:5432/budgetbuddy
      NODE_ENV: production
      RENDER: "true"
    depends_on:
      - postgres

volumes:
  postgres_data:
